-- CreateEnum
CREATE TYPE "InspectionStandardStatus" AS ENUM ('DRAFT', 'ACTIVE', 'SUPERSEDED', 'INACTIVE');

-- CreateEnum
CREATE TYPE "InputType" AS ENUM ('NONE', 'NUMERIC', 'ATTACHMENT', 'TEXT');

-- CreateTable
CREATE TABLE "QMS_INSPECTION_STANDARD" (
    "STANDARD_ID" VARCHAR(50) NOT NULL,
    "STANDARD_NO" VARCHAR(50) NOT NULL,
    "SUPPLIER_CODE" VARCHAR(50) NOT NULL,
    "SUPPLIER_NAME" VARCHAR(200),
    "ITEM_CODE" VARCHAR(50) NOT NULL,
    "ITEM_NAME" VARCHAR(200),
    "VERSION" INTEGER NOT NULL DEFAULT 1,
    "STATUS" "InspectionStandardStatus" NOT NULL DEFAULT 'DRAFT',
    "EFFECTIVE_DATE" TIMESTAMP(3),
    "EXPIRY_DATE" TIMESTAMP(3),
    "APPROVED_BY" VARCHAR(100),
    "APPROVED_DATE" TIMESTAMP(3),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_INSPECTION_STANDARD_pkey" PRIMARY KEY ("STANDARD_ID")
);

-- CreateTable
CREATE TABLE "QMS_INSPECTION_STANDARD_ITEM" (
    "STANDARD_ITEM_ID" VARCHAR(50) NOT NULL,
    "STANDARD_ID" VARCHAR(50) NOT NULL,
    "SEQUENCE_NO" INTEGER NOT NULL DEFAULT 1,
    "CHARACTERISTIC_NAME" VARCHAR(200) NOT NULL,
    "CHARACTERISTIC_NO" VARCHAR(50),
    "APPLICABLE_TYPES" VARCHAR(100),
    "INPUT_TYPE" "InputType" NOT NULL DEFAULT 'NONE',
    "SPEC_MIN" DECIMAL(18,6),
    "SPEC_MAX" DECIMAL(18,6),
    "SPEC_TEXT" VARCHAR(500),
    "UNIT" VARCHAR(20),
    "IS_CRITICAL" BOOLEAN NOT NULL DEFAULT false,
    "INSPECTION_METHOD" VARCHAR(200),
    "INSPECTION_EQUIPMENT" VARCHAR(200),
    "SAMPLING_LEVEL" VARCHAR(20),
    "AQL_LEVEL" VARCHAR(20),
    "REMARKS" VARCHAR(2000),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,
    "DELETED_AT" TIMESTAMP(3),
    "CREATED_BY" VARCHAR(100),
    "UPDATED_BY" VARCHAR(100),

    CONSTRAINT "QMS_INSPECTION_STANDARD_ITEM_pkey" PRIMARY KEY ("STANDARD_ITEM_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "QMS_INSPECTION_STANDARD_STANDARD_NO_key" ON "QMS_INSPECTION_STANDARD"("STANDARD_NO");

-- AddForeignKey
ALTER TABLE "QMS_INSPECTION_STANDARD_ITEM" ADD CONSTRAINT "QMS_INSPECTION_STANDARD_ITEM_STANDARD_ID_fkey" FOREIGN KEY ("STANDARD_ID") REFERENCES "QMS_INSPECTION_STANDARD"("STANDARD_ID") ON DELETE CASCADE ON UPDATE CASCADE;
